import 'package:appdemo/utilitaires/produit_adapter.dart';

class ProduitsData {
  static List<Produit> produits = [
    Produit(
      id: '1',
      nom: 'Adidas sl ',
      description: 'Une sneaker confortable et stylée.',
      prix: 12000.00,
      image: 'assets/images/Adidas-sl-72-rs.jpg',
      categorie: 'Sneakers',
      quantite: 1,
    ),
    Produit(
      id: '2',
      nom: 'Supernova Or-Noir',
      description: 'Maillot du supernova 2024.',
      prix: 5000.00,
      image: 'assets/images/maillot_noir_or_bms.png',
      categorie: 'T-shirts',
      quantite: 1,
    ),
    Produit(
      id: '3',
      nom: 'Casquette rouge',
      description: 'Une casquette tendance.',
      prix: 1900.00,
      image: 'assets/images/casquette1.jpg',
      categorie: 'Accessoires',
      quantite: 1,
    ),
    Produit(
      id: '4',
      nom: 'Jean Noir',
      description: 'Un jean classique et intemporel.',
      prix: 4900.00,
      image: 'assets/images/jean1.jpg',
      categorie: 'Jeans',
      quantite: 1,
    ),
    Produit(
      id: '5',
      nom: 'Jogging Marron',
      description: 'Confortables pour le sport.',
      prix: 7000.00,
      image: 'assets/images/jogging2.jpg',
      categorie: 'joggings',
      quantite: 1,
    ),
    Produit(
      id: '6',
      nom: 'Bracelet Argent',
      description: 'Un accessoire tendance pour compléter votre look.',
      prix: 1500.00,
      image: 'assets/images/bracelet2.jpg',
      categorie: 'Accessoires',
      quantite: 1,
    ),
    Produit(
      id: '7',
      nom: 'Nike-X-OnePiece Barbe Noire',
      description: 'Collab Nike-OnePiece.',
      prix: 18000.00,
      image: 'assets/images/Barbe-Noire-PUMA-x-ONE-PIECE.jpg',
      categorie: 'Sneakers',
      quantite: 1,
    ),
    Produit(
      id: '8',
      nom: 'Lustucru Bleu',
      description: 'Maillot bleu avec motif carré fini.',
      prix: 3000.00,
      image: 'assets/images/Maillotcarrefini_bms.png',
      categorie: 'T-shirts',
      quantite: 1,
    ),
    Produit(
      id: '9',
      nom: 'Casquette Sport',
      description: 'Une casquette idéale pour les activités sportives.',
      prix: 2000.00,
      image: 'assets/images/casquette2.jpg',
      categorie: 'Casquettes',
      quantite: 1,
    ),
    Produit(
      id: '10',
      nom: 'Nike sb dunk',
      description: 'Bakets aux couleurs modernes .',
      prix: 13000.00,
      image: 'assets/images/Sb_dunk_low_africa.jpg',
      categorie: 'Sneakers',
      quantite: 1,
    ),
  ];
}
